# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

use_frameworks!
workspace 'Marvelus'

def marvelus_pods
  pod 'SwiftGen', '~> 6.0'
  pod 'SwiftLint'
end

# MarvelusApp
target 'Marvelus' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'Marvelus.project'
  marvelus_pods
  # Pods for Marvelus

  target 'MarvelusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelusUITests' do
    # Pods for testing
  end

end

def core_pods
  marvelus_pods
end

#Core
target 'Core' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'Core/Core.project'
  core_pods
  # Pods for Core

  target 'CoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoreUITests' do
    # Pods for testing
  end

end
